global:
  scrape_interval: 15s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  # Cisco
  - job_name: 'ddwrt'
    scrape_interval: 10s
    scrape_timeout: 10s
    file_sd_configs:
        - files :
          - /etc/prometheus/dell.yml
          - /etc/prometheus/hp.yml
    # SNMP device.
    metrics_path: /snmp
    params:
      module: [snmp] #which OID's we will be querying in
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 172.17.0.7:9116  # The SNMP exporter's real hostname:port.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
