{
 "title": "Dell servers",
 "tags": [ "dashlinks" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "type",
    "query": "label_values(up{vendor=\"dell\"},vendor)"
   },
   {
    "name": "node",
    "query": "label_values(up{vendor=\"$type\"}, job)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Server basic information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(processorDeviceIndex{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(memoryDeviceSize{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemPowerState{job=\"$node\"}"
    }
   ]
  },
  {
   "title": "PS1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerSupplyStatus{job=\"$node\", powerSupplyIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "amperageProbeReading{job=\"$node\"} > 20"
    }
   ]
  },
  {
   "title": "FREQ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(processorDeviceCurrentSpeed{job=\"$node\"}) * 100/ sum(processorDeviceMaximumSpeed{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "CORES",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(processorDeviceCoreCount{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(physicalDiskCapacityInMB{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "PS2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerSupplyStatus{job=\"$node\", powerSupplyIndex=\"2\"}"
    }
   ]
  },
  { "title": "Server temperature sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Server temperature sensors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(temperatureProbeReading{job=\"$node\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{job=\"$node\"})",
     "legendFormat": "{{temperatureProbeLocationName}}"
    },
    {}
   ]
  },
  { "title": "Server hard disk information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(physicalDiskCapacityInMB{job=\"$node\"}) + on (physicalDiskNumber) group_left(physicalDiskDisplayName) (physicalDiskDisplayName{job=\"$node\"}) + on (physicalDiskNumber) group_left(physicalDiskProductID) (physicalDiskProductID{job=\"$node\"})  + on (physicalDiskNumber) group_left(physicalDiskSerialNo) (physicalDiskSerialNo{job=\"$node\"}) "
    },
    {
     "expr": "physicalDiskComponentStatus{job=\"$node\"}"
    }
   ]
  }
 ]
}