{
 "title": "HPE servers",
 "tags": [ "dashlinks" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "type",
    "query": "label_values(up{vendor=\"hp\"},vendor)"
   },
   {
    "name": "node",
    "query": "label_values(up{vendor=\"$type\"}, job)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Server basic info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cpqSeCpuUnitIndex{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cpqHeResMem2ModuleSize{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cpqSm2CntlrServerPowerState{job=\"$node\"}"
    }
   ]
  },
  {
   "title": "PS1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cpqHeFltTolPowerSupplyCondition{job=\"$node\", cpqHeFltTolPowerSupplyBay=\"1\"}"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "cpqHePowerMeterCurrReading{job=\"$node\"}"
    }
   ]
  },
  {
   "title": "FREQ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cpqSeCpuSpeed{job=\"$node\"})* 100 / sum(cpqSeCPUMaxSpeed{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "CORES",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cpqSeCpuCore{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cpqDaPhyDrvSize{job=\"$node\"})"
    }
   ]
  },
  {
   "title": "PS2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cpqHeFltTolPowerSupplyCondition{job=\"$node\", cpqHeFltTolPowerSupplyBay=\"2\"}"
    }
   ]
  },
  { "title": "Server temperature sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Server temperature sensors",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(cpqHeTemperatureCelsius{job=\"$node\"})",
     "legendFormat": "sensor: {{cpqHeTemperatureIndex}}"
    },
    {}
   ]
  },
  { "title": "Server hard disk information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Disk temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(cpqDaPhyDrvCurrentTemperature{job=\"$node\"}) + on (cpqDaPhyDrvIndex) group_left(cpqDaPhyDrvLocationString) (cpqDaPhyDrvLocationString{job=\"$node\"})",
     "legendFormat": "{{cpqDaPhyDrvLocationString}}"
    }
   ]
  },
  {
   "title": "Physical disks",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "(cpqDaPhyDrvSize{job=\"$node\"}) + on (cpqDaPhyDrvIndex) group_left(cpqDaPhyDrvLocationString) (cpqDaPhyDrvLocationString{job=\"$node\"}) + on (cpqDaPhyDrvIndex) group_left(cpqDaPhyDrvModel) (cpqDaPhyDrvModel{job=\"$node\"})  + on (cpqDaPhyDrvIndex) group_left(cpqDaPhyDrvSerialNum) (cpqDaPhyDrvSerialNum{job=\"$node\"})"
    },
    {
     "expr": "cpqDaPhyDrvStatus{job=\"$node\"}"
    }
   ]
  }
 ]
}