{
 "title": "Status",
 "tags": [ "dashlinks" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of physical CPU's",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(processorDeviceIndex) + count(cpqSeCpuUnitIndex)"
    }
   ]
  },
  {
   "title": "Number of all nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{device_type=\"hp\"} or up{device_type=\"dell\"})"
    }
   ]
  },
  {
   "title": "Number of HPE nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{device_type=\"hp\"})"
    }
   ]
  },
  {
   "title": "Number of all cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cpqSeCpuCore) + sum(processorDeviceCoreCount)"
    }
   ]
  },
  {
   "title": "Powered ON nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cpqSm2CntlrServerPowerState{device_type=\"hp\"} == 3 or systemPowerState{device_type=\"dell\"} == 4)"
    }
   ]
  },
  {
   "title": "Number of Dell nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{device_type=\"dell\"})"
    }
   ]
  },
  {
   "title": "Sum of all memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "kbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cpqHeResMem2ModuleSize) + sum(memoryDeviceSize)"
    }
   ]
  },
  {
   "title": "Powered OFF nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cpqSm2CntlrServerPowerState{device_type=\"hp\"} < 3 or systemPowerState{device_type=\"dell\"} < 4)"
    }
   ]
  },
  {
   "title": "Current power consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cpqHePowerMeterCurrReading) + sum(amperageProbeReading > 20)"
    }
   ]
  },
  {
   "title": "Sum of all online storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(physicalDiskCapacityInMB) + sum(cpqDaPhyDrvSize)"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Servers with disk issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(physicalDiskComponentStatus == 4 or cpqDaPhyDrvStatus == 3) "
    }
   ]
  },
  {
   "title": "RAID controller battery issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "cpqHeSysBatteryStatus != 1 or systemStateBatteryStatusCombined != 3"
    }
   ]
  },
  {
   "title": "Servers with disk issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "physicalDiskComponentStatus == 4 or cpqDaPhyDrvStatus == 3"
    }
   ]
  },
  {
   "title": "Power supply issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "cpqHeFltTolPowerSupplyCondition == 4 or powerSupplyStatus == 5"
    }
   ]
  },
  {
   "title": "RAID battery issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cpqHeSysBatteryStatus != 1 or systemStateBatteryStatusCombined != 3) "
    }
   ]
  },
  {
   "title": "Power supply issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cpqHeFltTolPowerSupplyCondition == 4 or powerSupplyStatus == 5) "
    }
   ]
  }
 ]
}