{
 "title": "Status",
 "tags": [ "dashlinks" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of physical CPU's",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(processorDeviceIndex) + count(cpqSeCpuUnitIndex)"
    }
   ]
  },
  {
   "title": "Number of all nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(up)" }
   ]
  },
  {
   "title": "Number of HPE nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{vendor=\"hp\"})"
    }
   ]
  },
  {
   "title": "Number of all cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cpqSeCpuCore) + sum(processorDeviceCoreCount)"
    }
   ]
  },
  {
   "title": "Powered ON nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cpqSm2CntlrServerPowerState{vendor=\"hp\"} == 3 or systemPowerState{vendor=\"dell\"} == 4)"
    }
   ]
  },
  {
   "title": "Number of Dell nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{vendor=\"dell\"})"
    }
   ]
  },
  {
   "title": "Sum of all memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "kbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cpqHeResMem2ModuleSize) + sum(memoryDeviceSize)"
    }
   ]
  },
  {
   "title": "Powered OFF nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(cpqSm2CntlrServerPowerState{vendor=\"hp\"} < 3 or systemPowerState{vendor=\"dell\"} < 4)"
    }
   ]
  },
  {
   "title": "Current power consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cpqHePowerMeterCurrReading) + sum(amperageProbeReading > 20)"
    }
   ]
  },
  {
   "title": "Sum of all online storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(physicalDiskCapacityInMB) + sum(cpqDaPhyDrvSize)"
    }
   ]
  }
 ]
}